import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'ar' | 'ru';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    welcome: "Welcome to Volga Services",
    subtitle: "Russia's premium tourist experience. We provide VIP transportation, seamless hotel bookings, curated event access, and unforgettable Russian adventures.",
    exploreServices: "Explore Services",
    languageSelector: "Language",
    backToHome: "Back to Home",
    ourServices: "Our Services",
    servicesSubtitle: "Discover our comprehensive range of premium services designed to make your Russian experience unforgettable.",
    allServices: "All Services",
    transportation: "Transportation",
    hotels: "Hotels",
    events: "Events",
    customTrips: "Custom Trips",
    bookNow: "Book Now",
    learnMore: "Learn More",
    luxuryTransport: "Luxury Transportation",
    luxuryTransportDesc: "Premium vehicles with professional drivers for your comfort and safety.",
    luxuryHotels: "Luxury Hotels",
    luxuryHotelsDesc: "Five-star accommodations in prime locations across Russia.",
    midrangeHotels: "Mid-Range Hotels",
    midrangeHotelsDesc: "Comfortable and affordable stays without compromising quality.",
    culturalEvents: "Cultural Events",
    culturalEventsDesc: "Exclusive access to concerts, festivals, and cultural shows.",
    groupTransport: "Group Transportation",
    groupTransportDesc: "Spacious buses and vans for group travel with flexible scheduling.",
    customTours: "Custom Tours",
    customToursDesc: "Personalized itineraries crafted to your interests and preferences.",
    professionalDrivers: "Professional Drivers",
    premiumVehicles: "Premium Vehicles",
    airportTransfers: "Airport Transfers",
    fiveStarHotels: "5-Star Hotels",
    primeLocations: "Prime Locations",
    conciergeService: "Concierge Service",
    comfortableStay: "Comfortable Stay",
    greatValue: "Great Value",
    modernAmenities: "Modern Amenities",
    exclusiveAccess: "Exclusive Access",
    culturalShows: "Cultural Shows",
    expertGuides: "Expert Guides",
    largeGroups: "Large Groups",
    comfortableBuses: "Comfortable Buses",
    flexibleSchedules: "Flexible Schedules",
    personalizedItinerary: "Personalized Itinerary",
    privateGuide: "Private Guide",
    flexibleDuration: "Flexible Duration",
    home: 'Home',
    about: 'About',
    contact: 'Contact',
    phone: 'Phone',
    email: 'Email',
    website: 'Website',
    address: 'Address',
    whatsapp: 'WhatsApp',
    contactInfo: 'Contact Information',
    businessInfo: 'Business Information',
    taxNumber: 'Tax Number',
    registrationNumber: 'Registration Number',
    followUs: 'Follow Us',
    allRightsReserved: 'All rights reserved.',
    footerDescription: 'Russia\'s premium tourist experience. VIP transportation, seamless hotel bookings, curated event access, and unforgettable Russian adventures.',
    aboutUs: 'About Us',
    contactUs: 'Contact Us',
    aboutDescription: 'Volga Services is Russia\'s premier tourism company, dedicated to providing exceptional travel experiences across the vast and beautiful landscapes of Russia. From the historic streets of Moscow and St. Petersburg to the pristine wilderness of Siberia, we offer comprehensive tourism solutions.',
    ourMission: 'Our Mission',
    missionDescription: 'To provide world-class tourism services that showcase the beauty, culture, and heritage of Russia while ensuring comfort, safety, and unforgettable experiences for our guests.',
    ourVision: 'Our Vision',
    visionDescription: 'To be the leading tourism company in Russia, recognized globally for excellence in service, innovation in travel solutions, and commitment to sustainable tourism practices.',
    // Booking page translations
    bookYourService: 'Book Your Service',
    chooseServiceDetails: 'Choose your service and provide the necessary details',
    selectServiceType: 'Select Service Type',
    chooseServiceYouNeed: 'Choose the service you need',
    hotelReservation: 'Hotel Reservation',
    eventBooking: 'Event Booking',
    customTrip: 'Custom Trip',
    serviceDetails: 'Service Details',
    provideSpecificInfo: 'Provide specific information for your selected service',
    contactInformation: 'Contact Information',
    contactInfoDesc: 'We\'ll use this information to contact you about your booking',
    pickupLocation: 'Pickup Location',
    dropoffLocation: 'Drop-off Location',
    enterPickupLocation: 'Enter pickup location',
    enterDropoffLocation: 'Enter drop-off location',
    date: 'Date',
    time: 'Time',
    vehicleType: 'Vehicle Type',
    selectVehicleType: 'Select vehicle type',
    sedan: 'Sedan',
    suv: 'SUV',
    minivan: 'Minivan',
    bus: 'Bus',
    city: 'City',
    hotel: 'Hotel',
    enterCityName: 'Enter city name',
    preferredHotel: 'Preferred hotel (optional)',
    checkinDate: 'Check-in Date',
    checkoutDate: 'Check-out Date',
    roomType: 'Room Type',
    selectRoomType: 'Select room type',
    singleRoom: 'Single Room',
    doubleRoom: 'Double Room',
    suite: 'Suite',
    familyRoom: 'Family Room',
    eventName: 'Event Name',
    eventLocation: 'Event Location',
    enterEventName: 'Enter event name',
    enterEventLocation: 'Enter event location',
    eventDate: 'Event Date',
    numberOfTickets: 'Number of Tickets',
    tripDuration: 'Trip Duration',
    selectDuration: 'Select duration',
    oneToDays: '1-3 days',
    fourToSevenDays: '4-7 days',
    oneToTwoWeeks: '1-2 weeks',
    threeToFourWeeks: '3-4 weeks',
    oneMonthPlus: '1 month+',
    regionsToVisit: 'Regions to Visit',
    describeRegions: 'Describe the regions or cities you\'d like to visit',
    interests: 'Interests (Select all that apply)',
    history: 'History',
    culture: 'Culture',
    nature: 'Nature',
    adventure: 'Adventure',
    food: 'Food',
    shopping: 'Shopping',
    nightlife: 'Nightlife',
    architecture: 'Architecture',
    museums: 'Museums',
    fullName: 'Full Name',
    emailAddress: 'Email Address',
    phoneNumber: 'Phone Number',
    preferredLanguage: 'Preferred Language',
    english: 'English',
    arabic: 'Arabic',
    russian: 'Russian',
    enterFullName: 'Enter your full name',
    enterEmail: 'Enter your email',
    enterPhone: 'Enter your phone number',
    selectLanguage: 'Select language',
    proceedToPayment: 'Proceed to Payment',
    // Payment page translations
    paymentAndConfirmation: 'Payment & Confirmation',
    reviewBookingComplete: 'Review your booking and complete the payment',
    bookingSummary: 'Booking Summary',
    paymentMethod: 'Payment Method',
    choosePaymentMethod: 'Choose your preferred payment method',
    bankTransfer: 'Bank Transfer',
    paypal: 'PayPal',
    bankTransferDetails: 'Bank Transfer Details',
    bankName: 'Bank Name',
    accountNumber: 'Account Number',
    swiftCode: 'SWIFT Code',
    iban: 'IBAN',
    beneficiary: 'Beneficiary',
    transferAmount: 'Please transfer the total amount and upload the payment receipt below. Our team will confirm your booking once payment is verified.',
    uploadPaymentReceipt: 'Upload Payment Receipt',
    fileUploaded: 'File uploaded',
    submitPaymentReceipt: 'Submit Payment Receipt',
    processing: 'Processing...',
    paypalPayment: 'PayPal Payment',
    paypalRedirect: 'You will be redirected to PayPal to complete your payment securely.',
    amountToCharge: 'Amount to be charged',
    payWithPaypal: 'Pay with PayPal',
    backToBooking: 'Back to Booking',
    total: 'Total',
    name: 'Name',
    language: 'Language',
    // Confirmation page translations
    bookingConfirmed: 'Booking Confirmed!',
    paymentPendingVerification: 'Payment Pending Verification',
    thankYouBooking: 'Thank you for your booking. You will receive a confirmation email shortly.',
    paymentReceiptReceived: 'Your payment receipt has been received. We will verify and confirm your booking within 24 hours.',
    bookingDetails: 'Booking Details',
    transactionReference: 'Your transaction reference and next steps',
    transactionId: 'Transaction ID',
    status: 'Status',
    confirmed: 'Confirmed',
    pendingVerification: 'Pending Verification',
    whatHappensNext: 'What happens next?',
    confirmationEmailSent: 'Confirmation Email Sent',
    checkEmailDetails: 'Check your email for detailed booking information',
    serviceCoordination: 'Service Coordination',
    teamContact: 'Our team will contact you within 2 hours to coordinate details',
    paymentVerification: 'Payment Verification',
    verifyingPayment: 'We are verifying your payment receipt (within 24 hours)',
    confirmationNotice: 'Confirmation Notice',
    emailConfirmation: 'You will receive an email confirmation once payment is verified',
    needHelp: 'Need help?',
    contactSupport: 'Contact our support team at',
    referenceTransaction: 'Please reference your transaction ID.',
    returnToHome: 'Return to Home',
    newBooking: 'New Booking',
    // Toast messages
    serviceRequired: 'Service required',
    pleaseSelectService: 'Please select a service type.',
    contactInfoRequired: 'Contact information required',
    fillRequiredFields: 'Please fill in all required contact fields.',
    receiptRequired: 'Receipt required',
    pleaseUploadReceipt: 'Please upload your payment receipt.',
    invalidFileType: 'Invalid file type',
    uploadValidFile: 'Please upload a PDF, JPG, or PNG file.',
    // PricingDisplay translations
    estimatedPrice: 'Estimated Price',
    estimatedPriceDisclaimer: 'This is an estimated price. Final cost will be confirmed after consultation with our team. Price may vary based on availability, season, and specific requirements.',
    // Payment method translations
    creditCard: 'Credit Card',
    creditCardDesc: 'Secure payment with your credit or debit card',
    paypalDesc: 'Pay securely with your PayPal account',
    cashOnArrival: 'Payment upon arrival (Cash on hand)',
    cashOnArrivalDesc: 'Pay cash when service is delivered - Contact via WhatsApp',
    cardNumber: 'Card Number',
    expiryDate: 'Expiry Date',
    cvv: 'CVV',
    cardholderName: 'Cardholder Name',
    enterCardNumber: 'Enter card number',
    enterExpiryDate: 'MM/YY',
    enterCvv: 'CVV',
    enterCardholderName: 'Enter cardholder name',
    payAmount: 'Pay Amount',
    customAmount: 'Custom Amount',
    enterCustomAmount: 'Enter custom amount',
    payNow: 'Pay Now',
    confirmBooking: 'Confirm Booking & Contact via WhatsApp',
    // Auth modal translations
    signIn: 'Sign In',
    signUp: 'Sign Up',
    forgotPassword: 'Forgot Password',
    signInWelcome: 'Welcome back! Please sign in to your account.',
    signUpWelcome: 'Create a new account to get started.',
    forgotPasswordWelcome: 'Enter your email and we\'ll send you a reset link.',
    createAccount: 'Create Account',
    resetYourPassword: 'Reset Your Password',
    enterCredentials: 'Enter your credentials to access your account',
    enterDetails: 'Enter your details to create a new account',
    emailResetLink: 'We will email you a password reset link',
    enterEmailPlaceholder: 'Enter your email',
    enterPhoneNumber: 'Enter your phone number',
    password: 'Password',
    enterPassword: 'Enter your password',
    loading: 'Loading...',
    sendResetEmail: 'Send Reset Email',
    dontHaveAccount: 'Don\'t have an account? Sign up',
    alreadyHaveAccount: 'Already have an account? Sign in',
    forgotPasswordLink: 'Forgot password?',
    backToSignIn: 'Back to sign in',
    // Toast messages for auth
    error: 'Error',
    success: 'Success',
    loggedInSuccessfully: 'Logged in successfully!',
    phoneNumberRequired: 'Phone number is required.',
    checkEmailVerify: 'Please check your email to verify your account.',
    passwordResetSent: 'Password reset email sent. Please check your inbox.',
    unexpectedError: 'An unexpected error occurred.',
    // Payment errors
    invalidAmount: 'Invalid amount',
    enterValidAmount: 'Please enter a valid payment amount greater than ₽0.',
    missingInformation: 'Missing information',
    fillCardDetails: 'Please fill in all credit card details.',
    invalidCardNumber: 'Invalid card number',
    enterValidCardNumber: 'Please enter a valid credit card number.',
    invalidExpiryDate: 'Invalid expiry date',
    expiryDateFormat: 'Please enter expiry date in MM/YY format.',
    invalidCvv: 'Invalid CVV',
    enterValidCvv: 'Please enter a valid CVV code.',
    paymentSuccessful: 'Payment successful!',
    paymentFailed: 'Payment failed',
    paymentErrorMessage: 'There was an error processing your payment. Please try again.',
    bookingSaved: 'Booking saved successfully!',
    bookingSavedDesc: 'Your booking has been saved to your account.',
    redirectingWhatsApp: 'Redirecting to WhatsApp for service arrangements...',
    paypalError: 'PayPal Error',
    paypalFailedLoad: 'Failed to load PayPal. Please try credit card instead.',
    paymentError: 'Payment error',
    paypalErrorOccurred: 'There was an error with PayPal. Please try again.',
    paymentCancelled: 'Payment cancelled',
    paypalPaymentCancelled: 'PayPal payment was cancelled.',
    // Service details
    customerInfo: 'Customer Information',
    // Dashboard
    dashboard: 'Dashboard',
    myReservations: 'My Reservations',
    settings: 'Settings',
    payments: 'Payments'
  },
  ar: {
    welcome: "مرحباً بكم في خدمات فولغا",
    subtitle: "تجربة السياحة الفاخرة في روسيا. نحن نوفر النقل المميز، حجوزات فندقية سلسة، الوصول المنسق للفعاليات، ومغامرات روسية لا تُنسى.",
    exploreServices: "استكشف الخدمات",
    languageSelector: "اللغة",
    backToHome: "العودة للرئيسية",
    ourServices: "خدماتنا",
    servicesSubtitle: "اكتشف مجموعتنا الشاملة من الخدمات المميزة المصممة لجعل تجربتك الروسية لا تُنسى.",
    allServices: "جميع الخدمات",
    transportation: "النقل",
    hotels: "الفنادق",
    events: "الفعاليات",
    customTrips: "رحلات مخصصة",
    bookNow: "احجز الآن",
    learnMore: "اعرف المزيد",
    luxuryTransport: "النقل الفاخر",
    luxuryTransportDesc: "مركبات فاخرة مع سائقين محترفين لراحتك وأمانك.",
    luxuryHotels: "فنادق فاخرة",
    luxuryHotelsDesc: "إقامة خمس نجوم في أفضل المواقع عبر روسيا.",
    midrangeHotels: "فنادق متوسطة",
    midrangeHotelsDesc: "إقامة مريحة وبأسعار معقولة دون التنازل عن الجودة.",
    culturalEvents: "فعاليات ثقافية",
    culturalEventsDesc: "وصول حصري للحفلات والمهرجانات والعروض الثقافية.",
    groupTransport: "نقل جماعي",
    groupTransportDesc: "حافلات وشاحنات واسعة للسفر الجماعي مع جداول مرنة.",
    customTours: "جولات مخصصة",
    customToursDesc: "برامج شخصية مصممة حسب اهتماماتك وتفضيلاتك.",
    professionalDrivers: "سائقون محترفون",
    premiumVehicles: "مركبات فاخرة",
    airportTransfers: "نقل المطار",
    fiveStarHotels: "فنادق 5 نجوم",
    primeLocations: "مواقع مميزة",
    conciergeService: "خدمة الكونسيرج",
    comfortableStay: "إقامة مريحة",
    greatValue: "قيمة ممتازة",
    modernAmenities: "مرافق حديثة",
    exclusiveAccess: "وصول حصري",
    culturalShows: "عروض ثقافية",
    expertGuides: "مرشدون خبراء",
    largeGroups: "مجموعات كبيرة",
    comfortableBuses: "حافلات مريحة",
    flexibleSchedules: "جداول مرنة",
    personalizedItinerary: "برنامج شخصي",
    privateGuide: "مرشد خاص",
    flexibleDuration: "مدة مرنة",
    home: 'الرئيسية',
    about: 'من نحن',
    contact: 'اتصل بنا',
    phone: 'الهاتف',
    email: 'البريد الإلكتروني',
    website: 'الموقع الإلكتروني',
    address: 'العنوان',
    whatsapp: 'واتساب',
    contactInfo: 'معلومات الاتصال',
    businessInfo: 'معلومات الشركة',
    taxNumber: 'الرقم الضريبي',
    registrationNumber: 'رقم التسجيل',
    followUs: 'تابعنا',
    allRightsReserved: 'جميع الحقوق محفوظة.',
    footerDescription: 'تجربة السياحة الروسية المتميزة. النقل الفاخر، حجوزات الفنادق السلسة، الوصول المنسق للفعاليات، والمغامرات الروسية التي لا تُنسى.',
    aboutUs: 'من نحن',
    contactUs: 'اتصل بنا',
    aboutDescription: 'فولجا سيرفيسز هي شركة السياحة الرائدة في روسيا، المكرسة لتقديم تجارب سفر استثنائية عبر المناظر الطبيعية الشاسعة والجميلة في روسيا. من شوارع موسكو وسانت بطرسبرغ التاريخية إلى البرية البكر في سيبيريا، نقدم حلول سياحية شاملة.',
    ourMission: 'مهمتنا',
    missionDescription: 'تقديم خدمات سياحية عالمية المستوى تُظهر جمال وثقافة وتراث روسيا مع ضمان الراحة والأمان والتجارب التي لا تُنسى لضيوفنا.',
    ourVision: 'رؤيتنا',
    visionDescription: 'أن نكون شركة السياحة الرائدة في روسيا، معترف بها عالمياً للتميز في الخدمة والابتكار في حلول السفر والالتزام بممارسات السياحة المستدامة.',
    // Booking page translations
    bookYourService: 'احجز خدمتك',
    chooseServiceDetails: 'اختر خدمتك وقدم التفاصيل المطلوبة',
    selectServiceType: 'اختر نوع الخدمة',
    chooseServiceYouNeed: 'اختر الخدمة التي تحتاجها',
    hotelReservation: 'حجز فندق',
    eventBooking: 'حجز فعالية',
    customTrip: 'رحلة مخصصة',
    serviceDetails: 'تفاصيل الخدمة',
    provideSpecificInfo: 'قدم معلومات محددة للخدمة المختارة',
    contactInformation: 'معلومات الاتصال',
    contactInfoDesc: 'سنستخدم هذه المعلومات للاتصال بك بشأن حجزك',
    pickupLocation: 'موقع الاستلام',
    dropoffLocation: 'موقع التسليم',
    enterPickupLocation: 'أدخل موقع الاستلام',
    enterDropoffLocation: 'أدخل موقع التسليم',
    date: 'التاريخ',
    time: 'الوقت',
    vehicleType: 'نوع المركبة',
    selectVehicleType: 'اختر نوع المركبة',
    sedan: 'سيدان',
    suv: 'دفع رباعي',
    minivan: 'فان صغير',
    bus: 'حافلة',
    city: 'المدينة',
    hotel: 'الفندق',
    enterCityName: 'أدخل اسم المدينة',
    preferredHotel: 'الفندق المفضل (اختياري)',
    checkinDate: 'تاريخ الوصول',
    checkoutDate: 'تاريخ المغادرة',
    roomType: 'نوع الغرفة',
    selectRoomType: 'اختر نوع الغرفة',
    singleRoom: 'غرفة فردية',
    doubleRoom: 'غرفة مزدوجة',
    suite: 'جناح',
    familyRoom: 'غرفة عائلية',
    eventName: 'اسم الفعالية',
    eventLocation: 'موقع الفعالية',
    enterEventName: 'أدخل اسم الفعالية',
    enterEventLocation: 'أدخل موقع الفعالية',
    eventDate: 'تاريخ الفعالية',
    numberOfTickets: 'عدد التذاكر',
    tripDuration: 'مدة الرحلة',
    selectDuration: 'اختر المدة',
    oneToDays: '1-3 أيام',
    fourToSevenDays: '4-7 أيام',
    oneToTwoWeeks: '1-2 أسبوع',
    threeToFourWeeks: '3-4 أسابيع',
    oneMonthPlus: 'شهر واحد+',
    regionsToVisit: 'المناطق للزيارة',
    describeRegions: 'صف المناطق أو المدن التي تود زيارتها',
    interests: 'الاهتمامات (اختر كل ما ينطبق)',
    history: 'التاريخ',
    culture: 'الثقافة',
    nature: 'الطبيعة',
    adventure: 'المغامرة',
    food: 'الطعام',
    shopping: 'التسوق',
    nightlife: 'الحياة الليلية',
    architecture: 'العمارة',
    museums: 'المتاحف',
    fullName: 'الاسم الكامل',
    emailAddress: 'عنوان البريد الإلكتروني',
    phoneNumber: 'رقم الهاتف',
    preferredLanguage: 'اللغة المفضلة',
    english: 'الإنجليزية',
    arabic: 'العربية',
    russian: 'الروسية',
    enterFullName: 'أدخل اسمك الكامل',
    enterEmail: 'أدخل بريدك الإلكتروني',
    enterPhone: 'أدخل رقم هاتفك',
    selectLanguage: 'اختر اللغة',
    proceedToPayment: 'متابعة للدفع',
    // Payment page translations
    paymentAndConfirmation: 'الدفع والتأكيد',
    reviewBookingComplete: 'راجع حجزك وأكمل الدفع',
    bookingSummary: 'ملخص الحجز',
    paymentMethod: 'طريقة الدفع',
    choosePaymentMethod: 'اختر طريقة الدفع المفضلة',
    bankTransfer: 'تحويل بنكي',
    paypal: 'باي بال',
    bankTransferDetails: 'تفاصيل التحويل البنكي',
    bankName: 'اسم البنك',
    accountNumber: 'رقم الحساب',
    swiftCode: 'رمز SWIFT',
    iban: 'رقم IBAN',
    beneficiary: 'المستفيد',
    transferAmount: 'يرجى تحويل المبلغ الإجمالي ورفع إيصال الدفع أدناه. سيؤكد فريقنا حجزك بمجرد التحقق من الدفع.',
    uploadPaymentReceipt: 'رفع إيصال الدفع',
    fileUploaded: 'تم رفع الملف',
    submitPaymentReceipt: 'إرسال إيصال الدفع',
    processing: 'جاري المعالجة...',
    paypalPayment: 'دفع باي بال',
    paypalRedirect: 'ستتم إعادة توجيهك إلى باي بال لإكمال دفعتك بأمان.',
    amountToCharge: 'المبلغ المراد تحصيله',
    payWithPaypal: 'ادفع بواسطة باي بال',
    backToBooking: 'العودة للحجز',
    total: 'الإجمالي',
    name: 'الاسم',
    language: 'اللغة',
    // Confirmation page translations
    bookingConfirmed: 'تم تأكيد الحجز!',
    paymentPendingVerification: 'الدفع في انتظار التحقق',
    thankYouBooking: 'شكراً لك على حجزك. ستتلقى بريد تأكيد قريباً.',
    paymentReceiptReceived: 'تم استلام إيصال دفعتك. سنتحقق ونؤكد حجزك خلال 24 ساعة.',
    bookingDetails: 'تفاصيل الحجز',
    transactionReference: 'مرجع المعاملة والخطوات التالية',
    transactionId: 'رقم المعاملة',
    status: 'الحالة',
    confirmed: 'مؤكد',
    pendingVerification: 'في انتظار التحقق',
    whatHappensNext: 'ما الذي يحدث بعد ذلك؟',
    confirmationEmailSent: 'تم إرسال بريد التأكيد',
    checkEmailDetails: 'تحقق من بريدك الإلكتروني للحصول على تفاصيل الحجز',
    serviceCoordination: 'تنسيق الخدمة',
    teamContact: 'سيتصل بك فريقنا خلال ساعتين لتنسيق التفاصيل',
    paymentVerification: 'التحقق من الدفع',
    verifyingPayment: 'نحن نتحقق من إيصال دفعتك (خلال 24 ساعة)',
    confirmationNotice: 'إشعار التأكيد',
    emailConfirmation: 'ستتلقى بريد تأكيد بمجرد التحقق من الدفع',
    needHelp: 'تحتاج مساعدة؟',
    contactSupport: 'اتصل بفريق الدعم على',
    referenceTransaction: 'يرجى الإشارة إلى رقم معاملتك.',
    returnToHome: 'العودة للرئيسية',
    newBooking: 'حجز جديد',
    // Toast messages
    serviceRequired: 'الخدمة مطلوبة',
    pleaseSelectService: 'يرجى اختيار نوع الخدمة.',
    contactInfoRequired: 'معلومات الاتصال مطلوبة',
    fillRequiredFields: 'يرجى ملء جميع الحقول المطلوبة للاتصال.',
    receiptRequired: 'الإيصال مطلوب',
    pleaseUploadReceipt: 'يرجى رفع إيصال الدفع.',
    invalidFileType: 'نوع ملف غير صالح',
    uploadValidFile: 'يرجى رفع ملف PDF أو JPG أو PNG.',
    // PricingDisplay translations
    estimatedPrice: 'السعر المقدر',
    estimatedPriceDisclaimer: 'هذا سعر تقديري. سيتم تأكيد التكلفة النهائية بعد التشاور مع فريقنا. قد يختلف السعر حسب التوفر والموسم والمتطلبات المحددة.',
    // Payment method translations
    creditCard: 'بطاقة ائتمان',
    creditCardDesc: 'دفع آمن ببطاقتك الائتمانية أو المصرفية',
    paypalDesc: 'ادفع بأمان باستخدام حساب PayPal الخاص بك',
    cashOnArrival: 'الدفع عند الوصول (نقداً)',
    cashOnArrivalDesc: 'ادفع نقداً عند تقديم الخدمة - اتصل عبر الواتساب',
    cardNumber: 'رقم البطاقة',
    expiryDate: 'تاريخ الانتهاء',
    cvv: 'CVV',
    cardholderName: 'اسم حامل البطاقة',
    enterCardNumber: 'أدخل رقم البطاقة',
    enterExpiryDate: 'شهر/سنة',
    enterCvv: 'CVV',
    enterCardholderName: 'أدخل اسم حامل البطاقة',
    payAmount: 'مبلغ الدفع',
    customAmount: 'مبلغ مخصص',
    enterCustomAmount: 'أدخل المبلغ المخصص',
    payNow: 'ادفع الآن',
    confirmBooking: 'تأكيد الحجز والاتصال عبر الواتساب',
    // Auth modal translations
    signIn: 'تسجيل الدخول',
    signUp: 'إنشاء حساب',
    forgotPassword: 'نسيت كلمة المرور',
    signInWelcome: 'أهلاً بعودتك! يرجى تسجيل الدخول إلى حسابك.',
    signUpWelcome: 'إنشاء حساب جديد للبدء.',
    forgotPasswordWelcome: 'أدخل بريدك الإلكتروني وسنرسل لك رابط إعادة التعيين.',
    createAccount: 'إنشاء حساب',
    resetYourPassword: 'إعادة تعيين كلمة المرور',
    enterCredentials: 'أدخل بياناتك للوصول إلى حسابك',
    enterDetails: 'أدخل بياناتك لإنشاء حساب جديد',
    emailResetLink: 'سنرسل لك رابط إعادة تعيين كلمة المرور بالبريد الإلكتروني',
    enterEmailPlaceholder: 'أدخل بريدك الإلكتروني',
    enterPhoneNumber: 'أدخل رقم هاتفك',
    password: 'كلمة المرور',
    enterPassword: 'أدخل كلمة المرور',
    loading: 'جاري التحميل...',
    sendResetEmail: 'إرسال بريد إعادة التعيين',
    dontHaveAccount: 'ليس لديك حساب؟ أنشئ حساباً',
    alreadyHaveAccount: 'لديك حساب بالفعل؟ سجل دخولك',
    forgotPasswordLink: 'نسيت كلمة المرور؟',
    backToSignIn: 'العودة لتسجيل الدخول',
    // Toast messages for auth
    error: 'خطأ',
    success: 'نجح',
    loggedInSuccessfully: 'تم تسجيل الدخول بنجاح!',
    phoneNumberRequired: 'رقم الهاتف مطلوب.',
    checkEmailVerify: 'يرجى التحقق من بريدك الإلكتروني للتحقق من حسابك.',
    passwordResetSent: 'تم إرسال بريد إعادة تعيين كلمة المرور. يرجى التحقق من صندوق الوارد.',
    unexpectedError: 'حدث خطأ غير متوقع.',
    // Payment errors
    invalidAmount: 'مبلغ غير صحيح',
    enterValidAmount: 'يرجى إدخال مبلغ دفع صحيح أكبر من ₽0.',
    missingInformation: 'معلومات مفقودة',
    fillCardDetails: 'يرجى ملء جميع تفاصيل البطاقة الائتمانية.',
    invalidCardNumber: 'رقم بطاقة غير صحيح',
    enterValidCardNumber: 'يرجى إدخال رقم بطاقة ائتمانية صحيح.',
    invalidExpiryDate: 'تاريخ انتهاء غير صحيح',
    expiryDateFormat: 'يرجى إدخال تاريخ الانتهاء بصيغة شهر/سنة.',
    invalidCvv: 'CVV غير صحيح',
    enterValidCvv: 'يرجى إدخال رمز CVV صحيح.',
    paymentSuccessful: 'تم الدفع بنجاح!',
    paymentFailed: 'فشل الدفع',
    paymentErrorMessage: 'حدث خطأ في معالجة دفعتك. يرجى المحاولة مرة أخرى.',
    bookingSaved: 'تم حفظ الحجز بنجاح!',
    bookingSavedDesc: 'تم حفظ حجزك في حسابك.',
    redirectingWhatsApp: 'جاري التوجيه إلى الواتساب لترتيبات الخدمة...',
    paypalError: 'خطأ في PayPal',
    paypalFailedLoad: 'فشل في تحميل PayPal. يرجى استخدام البطاقة الائتمانية بدلاً من ذلك.',
    paymentError: 'خطأ في الدفع',
    paypalErrorOccurred: 'حدث خطأ مع PayPal. يرجى المحاولة مرة أخرى.',
    paymentCancelled: 'تم إلغاء الدفع',
    paypalPaymentCancelled: 'تم إلغاء دفع PayPal.',
    // Service details
    customerInfo: 'معلومات العميل',
    // Dashboard
    dashboard: 'لوحة التحكم',
    myReservations: 'حجوزاتي',
    settings: 'الإعدادات',
    payments: 'المدفوعات'
  },
  ru: {
    welcome: "Добро пожаловать в Волга Сервис",
    subtitle: "Премиальный туристический опыт России. Мы предоставляем VIP-транспорт, бесшовное бронирование отелей, курируемый доступ к мероприятиям и незабываемые русские приключения.",
    exploreServices: "Изучить Услуги",
    languageSelector: "Язык",
    backToHome: "Вернуться домой",
    ourServices: "Наши Услуги",
    servicesSubtitle: "Откройте для себя наш полный спектр премиальных услуг, созданных для того, чтобы ваш российский опыт стал незабываемым.",
    allServices: "Все Услуги",
    transportation: "Транспорт",
    hotels: "Отели",
    events: "События",
    customTrips: "Индивидуальные Поездки",
    bookNow: "Забронировать",
    learnMore: "Узнать Больше",
    luxuryTransport: "Роскошный Транспорт",
    luxuryTransportDesc: "Премиальные автомобили с профессиональными водителями для вашего комфорта и безопасности.",
    luxuryHotels: "Роскошные Отели",
    luxuryHotelsDesc: "Пятизвездочные номера в лучших локациях по всей России.",
    midrangeHotels: "Отели Среднего Класса",
    midrangeHotelsDesc: "Комфортное и доступное размещение без компромиссов в качестве.",
    culturalEvents: "Культурные События",
    culturalEventsDesc: "Эксклюзивный доступ к концертам, фестивалям и культурным шоу.",
    groupTransport: "Групповой Транспорт",
    groupTransportDesc: "Просторные автобусы и фургоны для группового путешествия с гибким расписанием.",
    customTours: "Индивидуальные Туры",
    customToursDesc: "Персонализированные маршруты, созданные в соответствии с вашими интересами и предпочтениями.",
    professionalDrivers: "Профессиональные Водители",
    premiumVehicles: "Премиум Автомобили",
    airportTransfers: "Трансферы из Аэропорта",
    fiveStarHotels: "5-Звездочные Отели",
    primeLocations: "Лучшие Локации",
    conciergeService: "Служба Консьержа",
    comfortableStay: "Комфортное Пребывание",
    greatValue: "Отличное Соотношение",
    modernAmenities: "Современные Удобства",
    exclusiveAccess: "Эксклюзивный Доступ",
    culturalShows: "Культурные Шоу",
    expertGuides: "Эксперт Гиды",
    largeGroups: "Большие Группы",
    comfortableBuses: "Комфортные Автобусы",
    flexibleSchedules: "Гибкое Расписание",
    personalizedItinerary: "Персональный Маршрут",
    privateGuide: "Частный Гид",
    flexibleDuration: "Гибкая Продолжительность",
    home: 'Главная',
    about: 'О нас',
    contact: 'Контакты',
    phone: 'Телефон',
    email: 'Электронная почта',
    website: 'Веб-сайт',
    address: 'Адрес',
    whatsapp: 'WhatsApp',
    contactInfo: 'Контактная информация',
    businessInfo: 'Информация о компании',
    taxNumber: 'Налоговый номер',
    registrationNumber: 'Регистрационный номер',
    followUs: 'Подписывайтесь',
    allRightsReserved: 'Все права защищены.',
    footerDescription: 'Премиальный туристический опыт России. VIP транспорт, бесшовное бронирование отелей, кураторский доступ к мероприятиям и незабываемые русские приключения.',
    aboutUs: 'О нас',
    contactUs: 'Связаться с нами',
    aboutDescription: 'Волга Сервисы - ведущая туристическая компания России, посвященная предоставлению исключительных туристических впечатлений по обширным и красивым ландшафтам России. От исторических улиц Москвы и Санкт-Петербурга до нетронутой дикой природы Сибири, мы предлагаем комплексные туристические решения.',
    ourMission: 'Наша миссия',
    missionDescription: 'Предоставлять туристические услуги мирового класса, которые демонстрируют красоту, культуру и наследие России, обеспечивая при этом комфорт, безопасность и незабываемые впечатления для наших гостей.',
    ourVision: 'Наше видение',
    visionDescription: 'Быть ведущей туристической компанией в России, признанной во всем мире за превосходство в обслуживании, инновации в туристических решениях и приверженность устойчивым туристическим практикам.',
    // Booking page translations
    bookYourService: 'Забронировать Услугу',
    chooseServiceDetails: 'Выберите услугу и предоставьте необходимые детали',
    selectServiceType: 'Выберите Тип Услуги',
    chooseServiceYouNeed: 'Выберите нужную услугу',
    hotelReservation: 'Бронирование Отеля',
    eventBooking: 'Бронирование События',
    customTrip: 'Индивидуальная Поездка',
    serviceDetails: 'Детали Услуги',
    provideSpecificInfo: 'Предоставьте конкретную информацию для выбранной услуги',
    contactInformation: 'Контактная Информация',
    contactInfoDesc: 'Мы используем эту информацию для связи с вами по поводу вашего бронирования',
    pickupLocation: 'Место Подачи',
    dropoffLocation: 'Место Высадки',
    enterPickupLocation: 'Введите место подачи',
    enterDropoffLocation: 'Введите место высадки',
    date: 'Дата',
    time: 'Время',
    vehicleType: 'Тип Транспорта',
    selectVehicleType: 'Выберите тип транспорта',
    sedan: 'Седан',
    suv: 'Внедорожник',
    minivan: 'Минивэн',
    bus: 'Автобус',
    city: 'Город',
    hotel: 'Отель',
    enterCityName: 'Введите название города',
    preferredHotel: 'Предпочитаемый отель (необязательно)',
    checkinDate: 'Дата Заезда',
    checkoutDate: 'Дата Выезда',
    roomType: 'Тип Номера',
    selectRoomType: 'Выберите тип номера',
    singleRoom: 'Одноместный Номер',
    doubleRoom: 'Двухместный Номер',
    suite: 'Люкс',
    familyRoom: 'Семейный Номер',
    eventName: 'Название События',
    eventLocation: 'Место События',
    enterEventName: 'Введите название события',
    enterEventLocation: 'Введите место события',
    eventDate: 'Дата События',
    numberOfTickets: 'Количество Билетов',
    tripDuration: 'Продолжительность Поездки',
    selectDuration: 'Выберите продолжительность',
    oneToDays: '1-3 дня',
    fourToSevenDays: '4-7 дней',
    oneToTwoWeeks: '1-2 недели',
    threeToFourWeeks: '3-4 недели',
    oneMonthPlus: '1 месяц+',
    regionsToVisit: 'Регионы для Посещения',
    describeRegions: 'Опишите регионы или города, которые вы хотели бы посетить',
    interests: 'Интересы (Выберите все подходящие)',
    history: 'История',
    culture: 'Культура',
    nature: 'Природа',
    adventure: 'Приключения',
    food: 'Еда',
    shopping: 'Шопинг',
    nightlife: 'Ночная Жизнь',
    architecture: 'Архитектура',
    museums: 'Музеи',
    fullName: 'Полное Имя',
    emailAddress: 'Адрес Электронной Почты',
    phoneNumber: 'Номер Телефона',
    preferredLanguage: 'Предпочитаемый Язык',
    english: 'Английский',
    arabic: 'Арабский',
    russian: 'Русский',
    enterFullName: 'Введите ваше полное имя',
    enterEmail: 'Введите ваш email',
    enterPhone: 'Введите ваш номер телефона',
    selectLanguage: 'Выберите язык',
    proceedToPayment: 'Перейти к Оплате',
    // Payment page translations
    paymentAndConfirmation: 'Оплата и Подтверждение',
    reviewBookingComplete: 'Просмотрите ваше бронирование и завершите оплату',
    bookingSummary: 'Сводка Бронирования',
    paymentMethod: 'Способ Оплаты',
    choosePaymentMethod: 'Выберите предпочитаемый способ оплаты',
    bankTransfer: 'Банковский Перевод',
    paypal: 'PayPal',
    bankTransferDetails: 'Данные Банковского Перевода',
    bankName: 'Название Банка',
    accountNumber: 'Номер Счета',
    swiftCode: 'SWIFT Код',
    iban: 'IBAN',
    beneficiary: 'Получатель',
    transferAmount: 'Пожалуйста, переведите общую сумму и загрузите квитанцию об оплате ниже. Наша команда подтвердит ваше бронирование после верификации платежа.',
    uploadPaymentReceipt: 'Загрузить Квитанцию об Оплате',
    fileUploaded: 'Файл загружен',
    submitPaymentReceipt: 'Отправить Квитанцию об Оплате',
    processing: 'Обработка...',
    paypalPayment: 'Оплата PayPal',
    paypalRedirect: 'Вы будете перенаправлены в PayPal для безопасного завершения оплаты.',
    amountToCharge: 'Сумма к оплате',
    payWithPaypal: 'Оплатить через PayPal',
    backToBooking: 'Назад к Бронированию',
    total: 'Итого',
    name: 'Имя',
    language: 'Язык',
    // Confirmation page translations
    bookingConfirmed: 'Бронирование Подтверждено!',
    paymentPendingVerification: 'Платеж Ожидает Верификации',
    thankYouBooking: 'Спасибо за ваше бронирование. Вы получите подтверждающий email в ближайшее время.',
    paymentReceiptReceived: 'Ваша квитанция об оплате получена. Мы проверим и подтвердим ваше бронирование в течение 24 часов.',
    bookingDetails: 'Детали Бронирования',
    transactionReference: 'Ваш номер транзакции и следующие шаги',
    transactionId: 'ID Транзакции',
    status: 'Статус',
    confirmed: 'Подтверждено',
    pendingVerification: 'Ожидает Верификации',
    whatHappensNext: 'Что происходит дальше?',
    confirmationEmailSent: 'Подтверждающий Email Отправлен',
    checkEmailDetails: 'Проверьте вашу почту для подробной информации о бронировании',
    serviceCoordination: 'Координация Услуги',
    teamContact: 'Наша команда свяжется с вами в течение 2 часов для координации деталей',
    paymentVerification: 'Верификация Платежа',
    verifyingPayment: 'Мы проверяем вашу квитанцию об оплате (в течение 24 часов)',
    confirmationNotice: 'Уведомление о Подтверждении',
    emailConfirmation: 'Вы получите email подтверждение после верификации платежа',
    needHelp: 'Нужна помощь?',
    contactSupport: 'Свяжитесь с нашей службой поддержки по адресу',
    referenceTransaction: 'Пожалуйста, укажите ваш ID транзакции.',
    returnToHome: 'Вернуться на Главную',
    newBooking: 'Новое Бронирование',
    // Toast messages
    serviceRequired: 'Услуга обязательна',
    pleaseSelectService: 'Пожалуйста, выберите тип услуги.',
    contactInfoRequired: 'Контактная информация обязательна',
    fillRequiredFields: 'Пожалуйста, заполните все обязательные поля контактов.',
    receiptRequired: 'Квитанция обязательна',
    pleaseUploadReceipt: 'Пожалуйста, загрузите вашу квитанцию об оплате.',
    invalidFileType: 'Неверный тип файла',
    uploadValidFile: 'Пожалуйста, загрузите файл PDF, JPG или PNG.',
    // PricingDisplay translations
    estimatedPrice: 'Оценочная Цена',
    estimatedPriceDisclaimer: 'Это оценочная цена. Окончательная стоимость будет подтверждена после консультации с нашей командой. Цена может варьироваться в зависимости от доступности, сезона и конкретных требований.',
    // Payment method translations
    creditCard: 'Кредитная Карта',
    creditCardDesc: 'Безопасная оплата кредитной или дебетовой картой',
    paypalDesc: 'Безопасная оплата через ваш PayPal аккаунт',
    cashOnArrival: 'Оплата при прибытии (Наличными)',
    cashOnArrivalDesc: 'Оплата наличными при оказании услуги - Связь через WhatsApp',
    cardNumber: 'Номер Карты',
    expiryDate: 'Срок Действия',
    cvv: 'CVV',
    cardholderName: 'Имя Держателя Карты',
    enterCardNumber: 'Введите номер карты',
    enterExpiryDate: 'ММ/ГГ',
    enterCvv: 'CVV',
    enterCardholderName: 'Введите имя держателя карты',
    payAmount: 'Сумма Оплаты',
    customAmount: 'Пользовательская Сумма',
    enterCustomAmount: 'Введите пользовательскую сумму',
    payNow: 'Оплатить Сейчас',
    confirmBooking: 'Подтвердить Бронирование и Связаться через WhatsApp',
    // Auth modal translations
    signIn: 'Войти',
    signUp: 'Регистрация',
    forgotPassword: 'Забыли Пароль',
    signInWelcome: 'Добро пожаловать! Пожалуйста, войдите в свой аккаунт.',
    signUpWelcome: 'Создайте новый аккаунт для начала работы.',
    forgotPasswordWelcome: 'Введите ваш email и мы отправим ссылку для сброса.',
    createAccount: 'Создать Аккаунт',
    resetYourPassword: 'Сбросить Пароль',
    enterCredentials: 'Введите ваши данные для доступа к аккаунту',
    enterDetails: 'Введите ваши данные для создания нового аккаунта',
    emailResetLink: 'Мы отправим вам ссылку для сброса пароля по email',
    enterEmailPlaceholder: 'Введите ваш email',
    enterPhoneNumber: 'Введите ваш номер телефона',
    password: 'Пароль',
    enterPassword: 'Введите ваш пароль',
    loading: 'Загрузка...',
    sendResetEmail: 'Отправить Email для Сброса',
    dontHaveAccount: 'Нет аккаунта? Зарегистрируйтесь',
    alreadyHaveAccount: 'Уже есть аккаунт? Войдите',
    forgotPasswordLink: 'Забыли пароль?',
    backToSignIn: 'Вернуться ко входу',
    // Toast messages for auth
    error: 'Ошибка',
    success: 'Успех',
    loggedInSuccessfully: 'Успешный вход в систему!',
    phoneNumberRequired: 'Номер телефона обязателен.',
    checkEmailVerify: 'Пожалуйста, проверьте вашу почту для подтверждения аккаунта.',
    passwordResetSent: 'Email для сброса пароля отправлен. Пожалуйста, проверьте почту.',
    unexpectedError: 'Произошла неожиданная ошибка.',
    // Payment errors
    invalidAmount: 'Неверная сумма',
    enterValidAmount: 'Пожалуйста, введите корректную сумму оплаты больше ₽0.',
    missingInformation: 'Отсутствует информация',
    fillCardDetails: 'Пожалуйста, заполните все данные кредитной карты.',
    invalidCardNumber: 'Неверный номер карты',
    enterValidCardNumber: 'Пожалуйста, введите корректный номер кредитной карты.',
    invalidExpiryDate: 'Неверная дата истечения',
    expiryDateFormat: 'Пожалуйста, введите дату истечения в формате ММ/ГГ.',
    invalidCvv: 'Неверный CVV',
    enterValidCvv: 'Пожалуйста, введите корректный CVV код.',
    paymentSuccessful: 'Оплата успешна!',
    paymentFailed: 'Оплата не удалась',
    paymentErrorMessage: 'Произошла ошибка при обработке платежа. Пожалуйста, попробуйте снова.',
    bookingSaved: 'Бронирование сохранено успешно!',
    bookingSavedDesc: 'Ваше бронирование сохранено в вашем аккаунте.',
    redirectingWhatsApp: 'Перенаправление в WhatsApp для организации услуг...',
    paypalError: 'Ошибка PayPal',
    paypalFailedLoad: 'Не удалось загрузить PayPal. Пожалуйста, используйте кредитную карту.',
    paymentError: 'Ошибка платежа',
    paypalErrorOccurred: 'Произошла ошибка с PayPal. Пожалуйста, попробуйте снова.',
    paymentCancelled: 'Платеж отменен',
    paypalPaymentCancelled: 'Платеж PayPal был отменен.',
    // Service details
    customerInfo: 'Информация о Клиенте',
    // Dashboard
    dashboard: 'Панель Управления',
    myReservations: 'Мои Бронирования',
    settings: 'Настройки',
    payments: 'Платежи'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    const savedLanguage = localStorage.getItem('volga-language') as Language;
    if (savedLanguage && ['en', 'ar', 'ru'].includes(savedLanguage)) {
      setLanguage(savedLanguage);
    }
  }, []);

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('volga-language', lang);
    
    // Set document direction for Arabic
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};