// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tujborgbqzmcwolntvas.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR1amJvcmdicXptY3dvbG50dmFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MzA5OTAsImV4cCI6MjA2NTUwNjk5MH0.qByawNYD150swSVCkQoPRv3AAhgX2x1o2HME9UzakIY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);